
nameOverride: ""
fullnameOverride: ""
replicaCount: 1

controller:
  # Is the port the builds apis
  port: 10080
  # Is the port the store api
  apiPort: 10081
  # Is the port for the metrics service
  metricsPort: 9090
  # The namespace to run all the jobs in
  namespace: default
  # Configuration related to costs
  costs:
    # Name of the secret containing the infracost api token
    # Naming format of values found https://www.infracost.io/docs/features/environment_variables/
    secret: ""
  # Configuration for the images used by the jobs
  images:
    # is the default image to use for terraform operations
    terraform: hashicorp/terraform:1.1.9
    # infracosts is the image to use for infracosts
    infracosts: infracost/infracost:0.9.24
    # policy is image for policy
    policy: bridgecrew/checkov:2.0.1140
    # is the controller image
    controller: "quay.io/appvia/terraform-controller:v0.0.4"
    # The terraform image used when running jobs
    executor: "quay.io/appvia/terraform-executor:v0.0.4"
  # is the image pull policy
  imagePullPolicy: IfNotPresent
  # indicate we create the watcher jobs in user namespace, these allow users
  # to view the terraform output
  enableWatchers: true

  # The default terraform version (or tag of the above image)
  webhooks:
    # enables the webhooks
    enabled: true
    # is the port the webhooks is running
    port: 10081
    # creates the certificate authority
    ca: true
    # name of the file containing the certificate authority
    tlsAuthority: /certs/ca.pem
    # name of the file containing the tls certificate
    tlsCert: tls.pem
    # directory containing the above certificates
    tlsDir: /certs
    # name of the file containing the tls private key
    tlsKey: tls-key.pem

networkPolicies:
  # Indicates we should create the network policies
  enabled: true

imagePullSecrets: []

podAnnotations:
  prometheus.io/port: "9090"
  prometheus.io/scheme: "http"
  prometheus.io/scrape: "true"

podSecurityContext:
  fsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - all

rbac:
  # Indicates we should create all the rbac
  create: true
  # service account for the controller
  controller:
    # Indicates we should provision the rbac
    create: true
    # annotations is a collection of annotations which should be added
    annotations: {}

  # Configuration for the terraform executor service account
  executor:
    # indicates we should create the terraform-executor service account
    create: true
    # annotations is a collection of annotations which should be added
    annotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: name
              operator: In
              values:
              - controller
          topologyKey: failure-domain.beta.kubernetes.io/zone
      - weight: 95
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: name
              operator: In
              values:
              - controller
          topologyKey: kubernetes.io/hostname

