---
apiVersion: v2
name: terraform-controller
description: Controller used to provision a terraform workflow within kubernetes
type: application
version: 0.1.5
appVersion: 0.1.5
sources:
  - https://github.com/appvia/terraform-controller
  - https://github.com/appvia/terranetes
maintainers:
  - name: Appvia
    email: info@appvia.io
    url: https://appvia.io
