name: E2E

on:
  workflow_call:
    inputs:
      cloud:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      cloud:
        description: 'Cloud vendor to run against'
        required: true
        default: 'aws'
        type: choice
        options:
        - aws
        - azure
        - google

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Requirements
      run: |
        sudo apt update -y
        sudo apt install bats jq
    - name: Install Kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: v1.23.0
    - name: Install Kind
      run: |
        curl -sL https://github.com/kubernetes-sigs/kind/releases/download/v0.13.0/kind-linux-amd64 -o kind
        chmod +x kind
        kind create cluster
    - name: Load Images
      run: |
        VERSION=ci make controller-kind
    - name: E2E
      run: |
        test/e2e/check-suite.sh --cloud ${{ (github.event.inputs || inputs).cloud }}
      env:
        ARM_CLIENT_ID: ${{ secrets.E2E_ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.E2E_ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.E2E_ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.E2E_ARM_TENANT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.E2E_AWS_ACCESS_KEY_ID }}
        AWS_REGION: ${{ secrets.E2E_AWS_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.E2E_AWS_SECRET_ACCESS_KEY }}
