name: Release

on:
  push:
    tags:
    - "v*"

env:
  REGISTRY: quay.io
  REGISTRY_ORG: appvia

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: E2E
      uses: ./.github/workflows/e2e

  release:
    needs: e2e
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Docker Login
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD quay.io
    - name: Release Images
      run: make release-images
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
