name: Release

on:
  push:
    tags:
    - "v*"

env:
  REGISTRY: quay.io
  REGISTRY_ORG: appvia

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Verifying Images
      run: verify-images

  e2e:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Requirements
      run: |
        sudo apt update -y
        sudo apt install bats jq
    - name: E2E
      run: |
        test/e2e/check-suite.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.E2E_AWS_ACCESS_KEY_ID }}
        AWS_REGION: ${{ secrets.E2E_AWS_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.E2E_AWS_SECRET_ACCESS_KEY }}

  release:
    needs: [e2e, images]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Release Images
      run: make release-images
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}

