name: Release

on:
  push:
    tags:
    - "v*"

env:
  REGISTRY: quay.io
  REGISTRY_ORG: appvia

jobs:
  e2e-aws:
    uses: appvia/terraform-controller/.github/workflows/e2e.yaml@master
    secrets: inherit
    with:
      cloud: azure

  e2e-azure:
    uses: appvia/terraform-controller/.github/workflows/e2e.yaml@master
    secrets: inherit
    with:
      cloud: azure

  release-images:
    needs:
      - e2e-aws
      - e2e-azure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD quay.io
      - name: Release Images
        run: make release-images
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}

  release-helm:
    needs: release-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
