name: Release

on:
  push:
    tags:
    - "v*"

env:
  REGISTRY: quay.io
  REGISTRY_ORG: appvia

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.1'
    - name: Unit Tests
      run: make check

  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.1'
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        args: --timeout 1m

  release-images:
    needs: [linting, ci]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.1'
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    - name: Images
      run: make images
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
    - name: Release Images
      run: make release-images
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}

